import type { ModuleWorkspaceReadScope } from "../workspace-read-scope";

export const WORKSPACE_BOOTSTRAP_COLLECTIONS = Object.freeze([
  "staffRolePermissions",
] as const);

export const CUSTOMER_SCOPE_COLLECTIONS = Object.freeze([
  "customers",
  "sites",
  "areas",
  "workRequired",
  "measurementRevisions",
  "quotations",
  "acceptedScopes",
  "workOrders",
  "boqs",
  "purchaseOrders",
  "grns",
  "dispatches",
  "vendorBills",
  "vendorPayments",
  "contractorBills",
  "contractorPayments",
  "contractorBids",
  "contractorSettlements",
  "workOrderCostLines",
  "drawings",
  "executionLogs",
  "variationRequests",
  "visits",
  "tasks",
  "followups",
  "actions",
  "payments",
  "invoices",
  "customerReceipts",
  "blocked",
  "risks",
  "threads",
  "commSends",
  "entityFileAttachments",
  "entityReferenceAssignments",
  "commercialTerms",
  "paymentTermTemplates",
  "taxConfigs",
  "validityConfigs",
  "auditLog",
  "master.units",
  "master.workCategories",
  "master.workSubcategories",
  "master.articles",
  "master.articleVariants",
  "master.vendors",
  "master.contractors",
  "master.staff",
  "master.sourcePartners",
  "master.fileAssets",
] as const);

export const SITE_SCOPE_COLLECTIONS = Object.freeze([
  "customers",
  "sites",
  "areas",
  "workRequired",
  "measurementRevisions",
  "quotations",
  "acceptedScopes",
  "workOrders",
  "boqs",
  "vendorRfqs",
  "vendorBids",
  "purchaseOrders",
  "grns",
  "dispatches",
  "vendorBills",
  "vendorPayments",
  "contractorBills",
  "contractorPayments",
  "contractorBids",
  "contractorSettlements",
  "workOrderCostLines",
  "drawings",
  "executionLogs",
  "variationRequests",
  "visits",
  "tasks",
  "followups",
  "actions",
  "payments",
  "invoices",
  "customerReceipts",
  "blocked",
  "risks",
  "threads",
  "entityFileAttachments",
  "entityReferenceAssignments",
  "commercialTerms",
  "paymentTermTemplates",
  "taxConfigs",
  "validityConfigs",
  "auditLog",
  "master.units",
  "master.workCategories",
  "master.workSubcategories",
  "master.articles",
  "master.articleVariants",
  "master.subcategoryArticleMap",
  "master.workOptionGroups",
  "master.workOptionValues",
  "master.vendors",
  "master.contractors",
  "master.staff",
  "master.vendorRates",
  "master.contractorRates",
  "master.fileAssets",
] as const);

export const WORKDESK_SCOPE_COLLECTIONS = Object.freeze([
  "customers",
  "sites",
  "workRequired",
  "quotations",
  "workOrders",
  "purchaseOrders",
  "inventory",
  "stockMovements",
  "vendorBills",
  "vendorPayments",
  "contractorBills",
  "contractorPayments",
  "workOrderCostLines",
  "visits",
  "tasks",
  "followups",
  "actions",
  "payments",
  "invoices",
  "customerReceipts",
  "blocked",
  "risks",
  "threads",
  "attendance",
  "recurringTasks",
  "approvalPolicies",
  "commSends",
  "entityFileAttachments",
  "auditLog",
  "master.vendors",
  "master.contractors",
  "master.staff",
  "master.vendorRates",
  "master.vendorRateHistories",
  "master.fileAssets",
] as const);

export const QUOTATION_SCOPE_COLLECTIONS = Object.freeze([
  "customers",
  "sites",
  "areas",
  "workRequired",
  "measurementRevisions",
  "quotations",
  "acceptedScopes",
  "workOrders",
  "tasks",
  "followups",
  "actions",
  "payments",
  "invoices",
  "threads",
  "commSends",
  "entityFileAttachments",
  "entityReferenceAssignments",
  "commercialTerms",
  "paymentTermTemplates",
  "taxConfigs",
  "validityConfigs",
  "auditLog",
  "master.units",
  "master.workCategories",
  "master.workSubcategories",
  "master.articles",
  "master.articleVariants",
  "master.subcategoryArticleMap",
  "master.workOptionGroups",
  "master.workOptionValues",
  "master.staff",
  "master.sourcePartners",
  "master.customerRateSuggestions",
  "master.fileAssets",
] as const);

export const FIELD_SCOPE_COLLECTIONS = Object.freeze([
  "customers",
  "sites",
  "areas",
  "workRequired",
  "measurementRevisions",
  "workOrders",
  "drawings",
  "executionLogs",
  "variationRequests",
  "visits",
  "tasks",
  "followups",
  "actions",
  "blocked",
  "risks",
  "threads",
  "attendance",
  "entityFileAttachments",
  "auditLog",
  "master.vendors",
  "master.contractors",
  "master.staff",
  "master.fileAssets",
] as const);

export const PROCUREMENT_SCOPE_COLLECTIONS = Object.freeze([
  "customers",
  "sites",
  "areas",
  "workRequired",
  "workOrders",
  "boqs",
  "vendorRfqs",
  "vendorBids",
  "purchaseOrders",
  "grns",
  "inventory",
  "stockMovements",
  "dispatches",
  "vendorBills",
  "vendorPayments",
  "tasks",
  "actions",
  "threads",
  "entityFileAttachments",
  "taxConfigs",
  "auditLog",
  "master.units",
  "master.workCategories",
  "master.workSubcategories",
  "master.articles",
  "master.articleVariants",
  "master.subcategoryArticleMap",
  "master.vendors",
  "master.staff",
  "master.vendorRates",
  "master.vendorRateHistories",
  "master.fileAssets",
] as const);

export const FINANCE_SCOPE_COLLECTIONS = Object.freeze([
  "customers",
  "sites",
  "areas",
  "workRequired",
  "quotations",
  "acceptedScopes",
  "workOrders",
  "boqs",
  "purchaseOrders",
  "grns",
  "inventory",
  "stockMovements",
  "dispatches",
  "vendorBills",
  "vendorPayments",
  "contractorBills",
  "contractorPayments",
  "commissions",
  "workOrderCostLines",
  "contractorSettlements",
  "payments",
  "invoices",
  "customerReceipts",
  "tasks",
  "followups",
  "actions",
  "threads",
  "commercialTerms",
  "paymentTermTemplates",
  "taxConfigs",
  "auditLog",
  "master.vendors",
  "master.contractors",
  "master.staff",
  "master.sourcePartners",
  "master.commissionRules",
  "master.fileAssets",
] as const);

export const MEDIA_SCOPE_COLLECTIONS = Object.freeze([
  "customers",
  "sites",
  "quotations",
  "tasks",
  "followups",
  "threads",
  "commSends",
  "entityFileAttachments",
  "entityReferenceAssignments",
  "auditLog",
  "master.articles",
  "master.vendors",
  "master.staff",
  "master.storageAccounts",
  "master.storageFolderTemplates",
  "master.storageFolderInstances",
  "master.fileAssets",
  "master.catalogues",
  "master.catalogueArticleVendorLinks",
  "master.pinterestBoards",
  "master.referenceMedia",
] as const);

export const HR_SCOPE_COLLECTIONS = Object.freeze([
  "customers",
  "sites",
  "workOrders",
  "visits",
  "tasks",
  "followups",
  "threads",
  "attendance",
  "leaveRequests",
  "payrollPeriods",
  "payrollLines",
  "salaryAdjustments",
  "staffDocuments",
  "approvalPolicies",
  "entityFileAttachments",
  "auditLog",
  "master.contractors",
  "master.staff",
  "master.fileAssets",
] as const);

export const MASTER_SCOPE_COLLECTIONS = Object.freeze([
  "auditLog",
  "master.units",
  "master.workCategories",
  "master.workSubcategories",
  "master.articles",
  "master.articleVariants",
  "master.subcategoryArticleMap",
  "master.workOptionGroups",
  "master.workOptionValues",
] as const);

export const REPORTS_SCOPE_COLLECTIONS = Object.freeze([
  "customers",
  "sites",
  "areas",
  "workRequired",
  "measurementRevisions",
  "quotations",
  "acceptedScopes",
  "workOrders",
  "boqs",
  "vendorRfqs",
  "vendorBids",
  "purchaseOrders",
  "grns",
  "inventory",
  "stockMovements",
  "dispatches",
  "vendorBills",
  "vendorPayments",
  "contractorBills",
  "contractorPayments",
  "commissions",
  "workOrderCostLines",
  "contractorBids",
  "contractorSettlements",
  "drawings",
  "executionLogs",
  "variationRequests",
  "visits",
  "tasks",
  "followups",
  "actions",
  "payments",
  "invoices",
  "customerReceipts",
  "blocked",
  "risks",
  "attendance",
  "leaveRequests",
  "payrollPeriods",
  "payrollLines",
  "salaryAdjustments",
  "auditLog",
  "master.vendors",
  "master.contractors",
  "master.staff",
  "master.sourcePartners",
  "master.commissionRules",
] as const);

export const SYSTEM_SCOPE_COLLECTIONS = Object.freeze([
  "customers",
  "sites",
  "areas",
  "workRequired",
  "measurementRevisions",
  "quotations",
  "acceptedScopes",
  "workOrders",
  "boqs",
  "vendorRfqs",
  "vendorBids",
  "purchaseOrders",
  "grns",
  "inventory",
  "stockMovements",
  "dispatches",
  "vendorBills",
  "vendorPayments",
  "contractorBills",
  "contractorPayments",
  "commissions",
  "workOrderCostLines",
  "contractorBids",
  "contractorSettlements",
  "drawings",
  "executionLogs",
  "variationRequests",
  "visits",
  "tasks",
  "followups",
  "actions",
  "payments",
  "invoices",
  "customerReceipts",
  "blocked",
  "risks",
  "threads",
  "attendance",
  "staffRolePermissions",
  "leaveRequests",
  "payrollPeriods",
  "payrollLines",
  "salaryAdjustments",
  "staffDocuments",
  "approvalPolicies",
  "automationRules",
  "recurringTasks",
  "commSends",
  "entityFileAttachments",
  "entityReferenceAssignments",
  "auditLog",
  "master.units",
  "master.workCategories",
  "master.workSubcategories",
  "master.articles",
  "master.subcategoryArticleMap",
  "master.vendors",
  "master.contractors",
  "master.staff",
  "master.sourcePartners",
  "master.fileAssets",
] as const);

export const COLLECTIONS_BY_SCOPE: Readonly<
  Record<ModuleWorkspaceReadScope, readonly string[]>
> = Object.freeze({
  customer: CUSTOMER_SCOPE_COLLECTIONS,
  site: SITE_SCOPE_COLLECTIONS,
  workdesk: WORKDESK_SCOPE_COLLECTIONS,
  quotation: QUOTATION_SCOPE_COLLECTIONS,
  field: FIELD_SCOPE_COLLECTIONS,
  procurement: PROCUREMENT_SCOPE_COLLECTIONS,
  finance: FINANCE_SCOPE_COLLECTIONS,
  media: MEDIA_SCOPE_COLLECTIONS,
  hr: HR_SCOPE_COLLECTIONS,
  master: MASTER_SCOPE_COLLECTIONS,
  reports: REPORTS_SCOPE_COLLECTIONS,
  system: SYSTEM_SCOPE_COLLECTIONS,
});
