-- Restore the built-in staff role matrix when a relational workspace has no permission rows.
-- Existing customized permission rows are preserved.
with permission_rows (
  role_key, module_key, module_label,
  can_view, can_create, can_update, can_approve, can_delete
) as (
values
  ('OWNER', 'workspace', 'Workspace', true, true, true, true, true),
  ('OWNER', 'customers', 'Customers', true, true, true, true, true),
  ('OWNER', 'sites', 'Sites & Execution', true, true, true, true, true),
  ('OWNER', 'work', 'Work Required', true, true, true, true, true),
  ('OWNER', 'quotations', 'Quotations', true, true, true, true, true),
  ('OWNER', 'workOrders', 'Work Orders', true, true, true, true, true),
  ('OWNER', 'boqs', 'BOQ', true, true, true, true, true),
  ('OWNER', 'tasks', 'Tasks', true, true, true, true, true),
  ('OWNER', 'visits', 'Visits', true, true, true, true, true),
  ('OWNER', 'attendance', 'Attendance', true, true, true, true, true),
  ('OWNER', 'gps', 'GPS Tracking', true, true, true, true, true),
  ('OWNER', 'vendors', 'Vendors & Vendor Rates', true, true, true, true, true),
  ('OWNER', 'procurement', 'Procurement', true, true, true, true, true),
  ('OWNER', 'purchaseOrders', 'Purchase Orders', true, true, true, true, true),
  ('OWNER', 'grns', 'GRN / Receipts', true, true, true, true, true),
  ('OWNER', 'inventory', 'Inventory', true, true, true, true, true),
  ('OWNER', 'finance', 'Finance', true, true, true, true, true),
  ('OWNER', 'payroll', 'Payroll', true, true, true, true, true),
  ('OWNER', 'staff', 'Staff Master', true, true, true, true, true),
  ('OWNER', 'masters', 'Master Setup', true, true, true, true, true),
  ('OWNER', 'media', 'Files & Media', true, true, true, true, true),
  ('OWNER', 'approvals', 'Approvals & Control', true, true, true, true, true),
  ('OWNER', 'reports', 'Reports', true, true, true, true, true),
  ('OWNER', 'system', 'System', true, true, true, true, true),
  ('OPERATIONS_MANAGER', 'workspace', 'Workspace', true, false, false, false, false),
  ('OPERATIONS_MANAGER', 'customers', 'Customers', true, true, true, false, false),
  ('OPERATIONS_MANAGER', 'sites', 'Sites & Execution', true, true, true, true, false),
  ('OPERATIONS_MANAGER', 'work', 'Work Required', true, true, true, true, false),
  ('OPERATIONS_MANAGER', 'quotations', 'Quotations', true, true, true, true, false),
  ('OPERATIONS_MANAGER', 'workOrders', 'Work Orders', true, true, true, true, false),
  ('OPERATIONS_MANAGER', 'boqs', 'BOQ', true, true, true, true, false),
  ('OPERATIONS_MANAGER', 'tasks', 'Tasks', true, true, true, true, false),
  ('OPERATIONS_MANAGER', 'visits', 'Visits', true, true, true, true, false),
  ('OPERATIONS_MANAGER', 'attendance', 'Attendance', true, false, true, true, false),
  ('OPERATIONS_MANAGER', 'gps', 'GPS Tracking', true, false, false, false, false),
  ('OPERATIONS_MANAGER', 'vendors', 'Vendors & Vendor Rates', true, true, true, true, false),
  ('OPERATIONS_MANAGER', 'procurement', 'Procurement', true, true, true, true, false),
  ('OPERATIONS_MANAGER', 'purchaseOrders', 'Purchase Orders', true, true, true, true, false),
  ('OPERATIONS_MANAGER', 'grns', 'GRN / Receipts', true, true, true, true, false),
  ('OPERATIONS_MANAGER', 'inventory', 'Inventory', true, true, true, false, false),
  ('OPERATIONS_MANAGER', 'finance', 'Finance', true, false, false, false, false),
  ('OPERATIONS_MANAGER', 'payroll', 'Payroll', true, false, false, false, false),
  ('OPERATIONS_MANAGER', 'staff', 'Staff Master', true, true, true, true, false),
  ('OPERATIONS_MANAGER', 'masters', 'Master Setup', true, false, true, false, false),
  ('OPERATIONS_MANAGER', 'media', 'Files & Media', true, true, true, false, false),
  ('OPERATIONS_MANAGER', 'approvals', 'Approvals & Control', true, false, true, true, false),
  ('OPERATIONS_MANAGER', 'reports', 'Reports', true, false, false, false, false),
  ('OPERATIONS_MANAGER', 'system', 'System', true, false, false, false, false),
  ('FIELD_STAFF', 'workspace', 'Workspace', true, false, false, false, false),
  ('FIELD_STAFF', 'customers', 'Customers', false, false, false, false, false),
  ('FIELD_STAFF', 'sites', 'Sites & Execution', true, false, false, false, false),
  ('FIELD_STAFF', 'work', 'Work Required', true, false, false, false, false),
  ('FIELD_STAFF', 'quotations', 'Quotations', false, false, false, false, false),
  ('FIELD_STAFF', 'workOrders', 'Work Orders', false, false, false, false, false),
  ('FIELD_STAFF', 'boqs', 'BOQ', false, false, false, false, false),
  ('FIELD_STAFF', 'tasks', 'Tasks', true, false, true, false, false),
  ('FIELD_STAFF', 'visits', 'Visits', true, true, true, false, false),
  ('FIELD_STAFF', 'attendance', 'Attendance', true, true, true, false, false),
  ('FIELD_STAFF', 'gps', 'GPS Tracking', true, true, false, false, false),
  ('FIELD_STAFF', 'vendors', 'Vendors & Vendor Rates', false, false, false, false, false),
  ('FIELD_STAFF', 'procurement', 'Procurement', true, true, false, false, false),
  ('FIELD_STAFF', 'purchaseOrders', 'Purchase Orders', false, false, false, false, false),
  ('FIELD_STAFF', 'grns', 'GRN / Receipts', true, true, false, false, false),
  ('FIELD_STAFF', 'inventory', 'Inventory', true, false, false, false, false),
  ('FIELD_STAFF', 'finance', 'Finance', false, false, false, false, false),
  ('FIELD_STAFF', 'payroll', 'Payroll', false, false, false, false, false),
  ('FIELD_STAFF', 'staff', 'Staff Master', false, false, false, false, false),
  ('FIELD_STAFF', 'masters', 'Master Setup', false, false, false, false, false),
  ('FIELD_STAFF', 'media', 'Files & Media', true, true, false, false, false),
  ('FIELD_STAFF', 'approvals', 'Approvals & Control', false, false, false, false, false),
  ('FIELD_STAFF', 'reports', 'Reports', false, false, false, false, false),
  ('FIELD_STAFF', 'system', 'System', false, false, false, false, false),
  ('SALES_TELECALLER', 'workspace', 'Workspace', true, false, false, false, false),
  ('SALES_TELECALLER', 'customers', 'Customers', true, true, true, false, false),
  ('SALES_TELECALLER', 'sites', 'Sites & Execution', true, true, true, false, false),
  ('SALES_TELECALLER', 'work', 'Work Required', true, true, true, false, false),
  ('SALES_TELECALLER', 'quotations', 'Quotations', true, true, true, false, false),
  ('SALES_TELECALLER', 'workOrders', 'Work Orders', false, false, false, false, false),
  ('SALES_TELECALLER', 'boqs', 'BOQ', false, false, false, false, false),
  ('SALES_TELECALLER', 'tasks', 'Tasks', true, true, true, false, false),
  ('SALES_TELECALLER', 'visits', 'Visits', true, true, false, false, false),
  ('SALES_TELECALLER', 'attendance', 'Attendance', false, false, false, false, false),
  ('SALES_TELECALLER', 'gps', 'GPS Tracking', false, false, false, false, false),
  ('SALES_TELECALLER', 'vendors', 'Vendors & Vendor Rates', false, false, false, false, false),
  ('SALES_TELECALLER', 'procurement', 'Procurement', false, false, false, false, false),
  ('SALES_TELECALLER', 'purchaseOrders', 'Purchase Orders', false, false, false, false, false),
  ('SALES_TELECALLER', 'grns', 'GRN / Receipts', false, false, false, false, false),
  ('SALES_TELECALLER', 'inventory', 'Inventory', false, false, false, false, false),
  ('SALES_TELECALLER', 'finance', 'Finance', false, false, false, false, false),
  ('SALES_TELECALLER', 'payroll', 'Payroll', false, false, false, false, false),
  ('SALES_TELECALLER', 'staff', 'Staff Master', false, false, false, false, false),
  ('SALES_TELECALLER', 'masters', 'Master Setup', false, false, false, false, false),
  ('SALES_TELECALLER', 'media', 'Files & Media', true, true, false, false, false),
  ('SALES_TELECALLER', 'approvals', 'Approvals & Control', false, false, false, false, false),
  ('SALES_TELECALLER', 'reports', 'Reports', true, false, false, false, false),
  ('SALES_TELECALLER', 'system', 'System', false, false, false, false, false),
  ('PROCUREMENT_STAFF', 'workspace', 'Workspace', true, false, false, false, false),
  ('PROCUREMENT_STAFF', 'customers', 'Customers', false, false, false, false, false),
  ('PROCUREMENT_STAFF', 'sites', 'Sites & Execution', false, false, false, false, false),
  ('PROCUREMENT_STAFF', 'work', 'Work Required', false, false, false, false, false),
  ('PROCUREMENT_STAFF', 'quotations', 'Quotations', false, false, false, false, false),
  ('PROCUREMENT_STAFF', 'workOrders', 'Work Orders', false, false, false, false, false),
  ('PROCUREMENT_STAFF', 'boqs', 'BOQ', false, false, false, false, false),
  ('PROCUREMENT_STAFF', 'tasks', 'Tasks', false, false, false, false, false),
  ('PROCUREMENT_STAFF', 'visits', 'Visits', false, false, false, false, false),
  ('PROCUREMENT_STAFF', 'attendance', 'Attendance', false, false, false, false, false),
  ('PROCUREMENT_STAFF', 'gps', 'GPS Tracking', false, false, false, false, false),
  ('PROCUREMENT_STAFF', 'vendors', 'Vendors & Vendor Rates', true, true, true, false, false),
  ('PROCUREMENT_STAFF', 'procurement', 'Procurement', true, true, true, false, false),
  ('PROCUREMENT_STAFF', 'purchaseOrders', 'Purchase Orders', true, true, true, false, false),
  ('PROCUREMENT_STAFF', 'grns', 'GRN / Receipts', true, true, true, false, false),
  ('PROCUREMENT_STAFF', 'inventory', 'Inventory', true, true, true, false, false),
  ('PROCUREMENT_STAFF', 'finance', 'Finance', false, false, false, false, false),
  ('PROCUREMENT_STAFF', 'payroll', 'Payroll', false, false, false, false, false),
  ('PROCUREMENT_STAFF', 'staff', 'Staff Master', false, false, false, false, false),
  ('PROCUREMENT_STAFF', 'masters', 'Master Setup', true, false, false, false, false),
  ('PROCUREMENT_STAFF', 'media', 'Files & Media', true, true, false, false, false),
  ('PROCUREMENT_STAFF', 'approvals', 'Approvals & Control', false, false, false, false, false),
  ('PROCUREMENT_STAFF', 'reports', 'Reports', true, false, false, false, false),
  ('PROCUREMENT_STAFF', 'system', 'System', false, false, false, false, false),
  ('FINANCE', 'workspace', 'Workspace', true, false, false, false, false),
  ('FINANCE', 'customers', 'Customers', false, false, false, false, false),
  ('FINANCE', 'sites', 'Sites & Execution', false, false, false, false, false),
  ('FINANCE', 'work', 'Work Required', false, false, false, false, false),
  ('FINANCE', 'quotations', 'Quotations', true, false, false, false, false),
  ('FINANCE', 'workOrders', 'Work Orders', false, false, false, false, false),
  ('FINANCE', 'boqs', 'BOQ', false, false, false, false, false),
  ('FINANCE', 'tasks', 'Tasks', false, false, false, false, false),
  ('FINANCE', 'visits', 'Visits', false, false, false, false, false),
  ('FINANCE', 'attendance', 'Attendance', false, false, false, false, false),
  ('FINANCE', 'gps', 'GPS Tracking', false, false, false, false, false),
  ('FINANCE', 'vendors', 'Vendors & Vendor Rates', false, false, false, false, false),
  ('FINANCE', 'procurement', 'Procurement', true, false, false, false, false),
  ('FINANCE', 'purchaseOrders', 'Purchase Orders', true, false, false, false, false),
  ('FINANCE', 'grns', 'GRN / Receipts', true, false, false, false, false),
  ('FINANCE', 'inventory', 'Inventory', true, false, false, false, false),
  ('FINANCE', 'finance', 'Finance', true, true, true, true, false),
  ('FINANCE', 'payroll', 'Payroll', true, true, true, true, false),
  ('FINANCE', 'staff', 'Staff Master', true, false, false, false, false),
  ('FINANCE', 'masters', 'Master Setup', false, false, false, false, false),
  ('FINANCE', 'media', 'Files & Media', false, false, false, false, false),
  ('FINANCE', 'approvals', 'Approvals & Control', false, false, false, false, false),
  ('FINANCE', 'reports', 'Reports', true, false, false, false, false),
  ('FINANCE', 'system', 'System', false, false, false, false, false),
  ('ACCOUNTS_ADMIN', 'workspace', 'Workspace', true, false, false, false, false),
  ('ACCOUNTS_ADMIN', 'customers', 'Customers', false, false, false, false, false),
  ('ACCOUNTS_ADMIN', 'sites', 'Sites & Execution', false, false, false, false, false),
  ('ACCOUNTS_ADMIN', 'work', 'Work Required', false, false, false, false, false),
  ('ACCOUNTS_ADMIN', 'quotations', 'Quotations', false, false, false, false, false),
  ('ACCOUNTS_ADMIN', 'workOrders', 'Work Orders', false, false, false, false, false),
  ('ACCOUNTS_ADMIN', 'boqs', 'BOQ', false, false, false, false, false),
  ('ACCOUNTS_ADMIN', 'tasks', 'Tasks', false, false, false, false, false),
  ('ACCOUNTS_ADMIN', 'visits', 'Visits', false, false, false, false, false),
  ('ACCOUNTS_ADMIN', 'attendance', 'Attendance', false, false, false, false, false),
  ('ACCOUNTS_ADMIN', 'gps', 'GPS Tracking', false, false, false, false, false),
  ('ACCOUNTS_ADMIN', 'vendors', 'Vendors & Vendor Rates', false, false, false, false, false),
  ('ACCOUNTS_ADMIN', 'procurement', 'Procurement', true, false, false, false, false),
  ('ACCOUNTS_ADMIN', 'purchaseOrders', 'Purchase Orders', false, false, false, false, false),
  ('ACCOUNTS_ADMIN', 'grns', 'GRN / Receipts', false, false, false, false, false),
  ('ACCOUNTS_ADMIN', 'inventory', 'Inventory', true, false, false, false, false),
  ('ACCOUNTS_ADMIN', 'finance', 'Finance', true, true, true, false, false),
  ('ACCOUNTS_ADMIN', 'payroll', 'Payroll', true, true, true, false, false),
  ('ACCOUNTS_ADMIN', 'staff', 'Staff Master', false, false, false, false, false),
  ('ACCOUNTS_ADMIN', 'masters', 'Master Setup', false, false, false, false, false),
  ('ACCOUNTS_ADMIN', 'media', 'Files & Media', false, false, false, false, false),
  ('ACCOUNTS_ADMIN', 'approvals', 'Approvals & Control', false, false, false, false, false),
  ('ACCOUNTS_ADMIN', 'reports', 'Reports', true, false, false, false, false),
  ('ACCOUNTS_ADMIN', 'system', 'System', false, false, false, false, false)
)
insert into public."entity_staffRolePermissions" (
  id, workspace_id, revision, updated_at, updated_by, data
)
select
  'perm-' || lower(role_key) || '-' || module_key,
  'default',
  1,
  now(),
  'Default staff permission baseline',
  jsonb_build_object(
    'id', 'perm-' || lower(role_key) || '-' || module_key,
    'role_key', role_key,
    'module_key', module_key,
    'module_label', module_label,
    'can_view', can_view,
    'can_create', can_create,
    'can_update', can_update,
    'can_approve', can_approve,
    'can_delete', can_delete,
    'updated_at', now()::text
  )
from permission_rows
on conflict (id) do nothing;

update public.entity_workspace_revision
set revision = revision + 1,
    updated_at = now()
where id = 'default';
